# Generated by roxyassert: do not edit by hand.
# Re-generated on devtools::document(). Commit this file like NAMESPACE.

assert_args_DeribitMarketData__initialize <- function(base_url, async, max_tries, throttle_rate) {
  assert_scalar_character(base_url)
  assert_scalar_logical(async)
  assert_scalar_count(max_tries)
  assert_between(max_tries, lower = 1)
  if (!is.null(throttle_rate)) {
    assert_scalar_double(throttle_rate)
    assert_between(throttle_rate, lower = 0, lower_inclusive = FALSE, upper = Inf, upper_inclusive = FALSE)
  }
  return(invisible(NULL))
}

assert_return_DeribitMarketData__initialize <- function(value) {
  assert_class(value, "DeribitMarketData")
  return(value)
}

assert_args_DeribitMarketData__get_instruments <- function(currency, kind, expired) {
  assert_scalar_character(currency)
  if (!is.null(kind)) {
    assert_scalar_character(kind)
  }
  assert_scalar_logical(expired)
  return(invisible(NULL))
}

assert_return_DeribitMarketData__get_instruments <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("instrument_name", "instrument_id", "kind", "instrument_type", "base_currency", "quote_currency", "counter_currency", "settlement_currency", "settlement_period", "price_index", "is_active", "state", "expiration_datetime", "creation_datetime", "contract_size", "tick_size", "min_trade_amount", "maker_commission", "taker_commission", "strike", "option_type", "max_leverage"))
  assert_character(value[["instrument_name"]])
  assert_no_missing_values(value[["instrument_name"]])
  assert_integer(value[["instrument_id"]])
  assert_no_missing_values(value[["instrument_id"]])
  assert_character(value[["kind"]])
  assert_no_missing_values(value[["kind"]])
  assert_character(value[["instrument_type"]])
  assert_no_missing_values(value[["instrument_type"]])
  assert_character(value[["base_currency"]])
  assert_no_missing_values(value[["base_currency"]])
  assert_character(value[["quote_currency"]])
  assert_no_missing_values(value[["quote_currency"]])
  assert_character(value[["counter_currency"]])
  assert_no_missing_values(value[["counter_currency"]])
  assert_character(value[["settlement_currency"]])
  assert_character(value[["settlement_period"]])
  assert_no_missing_values(value[["settlement_period"]])
  assert_character(value[["price_index"]])
  assert_no_missing_values(value[["price_index"]])
  assert_logical(value[["is_active"]])
  assert_no_missing_values(value[["is_active"]])
  assert_character(value[["state"]])
  assert_no_missing_values(value[["state"]])
  assert_datetime(value[["expiration_datetime"]])
  assert_no_missing_values(value[["expiration_datetime"]])
  assert_datetime(value[["creation_datetime"]])
  assert_no_missing_values(value[["creation_datetime"]])
  assert_double(value[["contract_size"]])
  assert_no_missing_values(value[["contract_size"]])
  assert_double(value[["tick_size"]])
  assert_no_missing_values(value[["tick_size"]])
  assert_double(value[["min_trade_amount"]])
  assert_no_missing_values(value[["min_trade_amount"]])
  assert_double(value[["maker_commission"]])
  assert_no_missing_values(value[["maker_commission"]])
  assert_double(value[["taker_commission"]])
  assert_no_missing_values(value[["taker_commission"]])
  assert_double(value[["strike"]])
  assert_character(value[["option_type"]])
  assert_double(value[["max_leverage"]])
  return(value)
}

assert_return_DeribitMarketData__get_currencies <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("currency", "currency_long", "coin_type", "decimals", "min_confirmations", "min_withdrawal_fee", "withdrawal_fee", "network_fee", "in_cross_collateral_pool"))
  assert_character(value[["currency"]])
  assert_no_missing_values(value[["currency"]])
  assert_character(value[["currency_long"]])
  assert_no_missing_values(value[["currency_long"]])
  assert_character(value[["coin_type"]])
  assert_no_missing_values(value[["coin_type"]])
  assert_integer(value[["decimals"]])
  assert_integer(value[["min_confirmations"]])
  assert_double(value[["min_withdrawal_fee"]])
  assert_double(value[["withdrawal_fee"]])
  assert_double(value[["network_fee"]])
  assert_logical(value[["in_cross_collateral_pool"]])
  return(value)
}

assert_args_DeribitMarketData__get_ticker <- function(instrument_name) {
  assert_scalar_character(instrument_name)
  return(invisible(NULL))
}

assert_return_DeribitMarketData__get_ticker <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("instrument_name", "datetime", "state", "last_price", "mark_price", "index_price", "best_bid_price", "best_bid_amount", "best_ask_price", "best_ask_amount", "settlement_price", "min_price", "max_price", "open_interest", "mark_iv", "underlying_price", "interest_rate", "interest_value", "current_funding", "funding_8h", "estimated_delivery_price", "stats_high", "stats_low", "stats_price_change", "stats_volume", "stats_volume_usd", "stats_volume_notional", "greeks_delta", "greeks_gamma", "greeks_vega", "greeks_theta", "greeks_rho"))
  assert_character(value[["instrument_name"]])
  assert_no_missing_values(value[["instrument_name"]])
  assert_datetime(value[["datetime"]])
  assert_no_missing_values(value[["datetime"]])
  assert_character(value[["state"]])
  assert_no_missing_values(value[["state"]])
  assert_double(value[["last_price"]])
  assert_double(value[["mark_price"]])
  assert_double(value[["index_price"]])
  assert_double(value[["best_bid_price"]])
  assert_double(value[["best_bid_amount"]])
  assert_double(value[["best_ask_price"]])
  assert_double(value[["best_ask_amount"]])
  assert_double(value[["settlement_price"]])
  assert_double(value[["min_price"]])
  assert_double(value[["max_price"]])
  assert_double(value[["open_interest"]])
  assert_double(value[["mark_iv"]])
  assert_double(value[["underlying_price"]])
  assert_double(value[["interest_rate"]])
  assert_double(value[["interest_value"]])
  assert_double(value[["current_funding"]])
  assert_double(value[["funding_8h"]])
  assert_double(value[["estimated_delivery_price"]])
  assert_double(value[["stats_high"]])
  assert_double(value[["stats_low"]])
  assert_double(value[["stats_price_change"]])
  assert_double(value[["stats_volume"]])
  assert_double(value[["stats_volume_usd"]])
  assert_double(value[["stats_volume_notional"]])
  assert_double(value[["greeks_delta"]])
  assert_double(value[["greeks_gamma"]])
  assert_double(value[["greeks_vega"]])
  assert_double(value[["greeks_theta"]])
  assert_double(value[["greeks_rho"]])
  return(value)
}

assert_args_DeribitMarketData__get_order_book <- function(instrument_name, depth) {
  assert_scalar_character(instrument_name)
  if (!is.null(depth)) {
    assert_scalar_count(depth)
    assert_between(depth, lower = 1)
  }
  return(invisible(NULL))
}

assert_return_DeribitMarketData__get_order_book <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("instrument_name", "datetime", "side", "level", "price", "amount"))
  assert_character(value[["instrument_name"]])
  assert_no_missing_values(value[["instrument_name"]])
  assert_datetime(value[["datetime"]])
  assert_no_missing_values(value[["datetime"]])
  assert_character(value[["side"]])
  assert_no_missing_values(value[["side"]])
  assert_integer(value[["level"]])
  assert_no_missing_values(value[["level"]])
  assert_double(value[["price"]])
  assert_no_missing_values(value[["price"]])
  assert_double(value[["amount"]])
  assert_no_missing_values(value[["amount"]])
  return(value)
}

assert_args_DeribitMarketData__get_index_price <- function(index_name) {
  assert_scalar_character(index_name)
  return(invisible(NULL))
}

assert_return_DeribitMarketData__get_index_price <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("index_name", "index_price", "estimated_delivery_price"))
  assert_character(value[["index_name"]])
  assert_no_missing_values(value[["index_name"]])
  assert_double(value[["index_price"]])
  assert_double(value[["estimated_delivery_price"]])
  return(value)
}

assert_args_DeribitMarketData__get_volatility_index_data <- function(currency, start_timestamp, end_timestamp, resolution) {
  assert_scalar_character(currency)
  assert_class(start_timestamp, "POSIXct")
  assert_class(end_timestamp, "POSIXct")
  assert_scalar_character(resolution)
  return(invisible(NULL))
}

assert_return_DeribitMarketData__get_volatility_index_data <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("currency", "datetime", "resolution", "open", "high", "low", "close"))
  assert_character(value[["currency"]])
  assert_no_missing_values(value[["currency"]])
  assert_datetime(value[["datetime"]])
  assert_no_missing_values(value[["datetime"]])
  assert_character(value[["resolution"]])
  assert_no_missing_values(value[["resolution"]])
  assert_double(value[["open"]])
  assert_no_missing_values(value[["open"]])
  assert_double(value[["high"]])
  assert_no_missing_values(value[["high"]])
  assert_double(value[["low"]])
  assert_no_missing_values(value[["low"]])
  assert_double(value[["close"]])
  assert_no_missing_values(value[["close"]])
  return(value)
}

assert_args_DeribitMarketData__get_funding_rate_history <- function(instrument_name, start_timestamp, end_timestamp) {
  assert_scalar_character(instrument_name)
  assert_class(start_timestamp, "POSIXct")
  assert_class(end_timestamp, "POSIXct")
  return(invisible(NULL))
}

assert_return_DeribitMarketData__get_funding_rate_history <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("instrument_name", "datetime", "index_price", "prev_index_price", "interest_8h", "interest_1h"))
  assert_character(value[["instrument_name"]])
  assert_no_missing_values(value[["instrument_name"]])
  assert_datetime(value[["datetime"]])
  assert_no_missing_values(value[["datetime"]])
  assert_double(value[["index_price"]])
  assert_double(value[["prev_index_price"]])
  assert_double(value[["interest_8h"]])
  assert_double(value[["interest_1h"]])
  return(value)
}

assert_args_DeribitMarketData__get_funding_rate_value <- function(instrument_name, start_timestamp, end_timestamp) {
  assert_scalar_character(instrument_name)
  assert_class(start_timestamp, "POSIXct")
  assert_class(end_timestamp, "POSIXct")
  return(invisible(NULL))
}

assert_return_DeribitMarketData__get_funding_rate_value <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("instrument_name", "start_datetime", "end_datetime", "funding_rate_value"))
  assert_character(value[["instrument_name"]])
  assert_no_missing_values(value[["instrument_name"]])
  assert_datetime(value[["start_datetime"]])
  assert_no_missing_values(value[["start_datetime"]])
  assert_datetime(value[["end_datetime"]])
  assert_no_missing_values(value[["end_datetime"]])
  assert_double(value[["funding_rate_value"]])
  return(value)
}

assert_args_DeribitMarketData__get_last_trades_by_instrument <- function(instrument_name, count, start_timestamp, end_timestamp, sorting) {
  assert_scalar_character(instrument_name)
  if (!is.null(count)) {
    assert_scalar_count(count)
    assert_between(count, lower = 1)
  }
  if (!is.null(start_timestamp)) {
    assert_class(start_timestamp, "POSIXct")
  }
  if (!is.null(end_timestamp)) {
    assert_class(end_timestamp, "POSIXct")
  }
  if (!is.null(sorting)) {
    assert_scalar_character(sorting)
  }
  return(invisible(NULL))
}

assert_return_DeribitMarketData__get_last_trades_by_instrument <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("trade_id", "instrument_name", "datetime", "trade_seq", "direction", "price", "amount", "index_price", "mark_price", "iv", "tick_direction", "contracts", "liquidation"))
  assert_character(value[["trade_id"]])
  assert_no_missing_values(value[["trade_id"]])
  assert_character(value[["instrument_name"]])
  assert_no_missing_values(value[["instrument_name"]])
  assert_datetime(value[["datetime"]])
  assert_no_missing_values(value[["datetime"]])
  assert_integer(value[["trade_seq"]])
  assert_character(value[["direction"]])
  assert_no_missing_values(value[["direction"]])
  assert_double(value[["price"]])
  assert_no_missing_values(value[["price"]])
  assert_double(value[["amount"]])
  assert_no_missing_values(value[["amount"]])
  assert_double(value[["index_price"]])
  assert_double(value[["mark_price"]])
  assert_double(value[["iv"]])
  assert_integer(value[["tick_direction"]])
  assert_double(value[["contracts"]])
  assert_character(value[["liquidation"]])
  return(value)
}

assert_args_DeribitMarketData__get_book_summary_by_currency <- function(currency, kind) {
  assert_scalar_character(currency)
  if (!is.null(kind)) {
    assert_scalar_character(kind)
  }
  return(invisible(NULL))
}

assert_return_DeribitMarketData__get_book_summary_by_currency <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("instrument_name", "base_currency", "quote_currency", "datetime", "mid_price", "bid_price", "ask_price", "last", "mark_price", "high", "low", "open_interest", "volume", "volume_usd", "volume_notional", "price_change", "estimated_delivery_price", "mark_iv", "underlying_price", "underlying_index", "interest_rate", "current_funding", "funding_8h"))
  assert_character(value[["instrument_name"]])
  assert_no_missing_values(value[["instrument_name"]])
  assert_character(value[["base_currency"]])
  assert_no_missing_values(value[["base_currency"]])
  assert_character(value[["quote_currency"]])
  assert_no_missing_values(value[["quote_currency"]])
  assert_datetime(value[["datetime"]])
  assert_no_missing_values(value[["datetime"]])
  assert_double(value[["mid_price"]])
  assert_double(value[["bid_price"]])
  assert_double(value[["ask_price"]])
  assert_double(value[["last"]])
  assert_double(value[["mark_price"]])
  assert_double(value[["high"]])
  assert_double(value[["low"]])
  assert_double(value[["open_interest"]])
  assert_double(value[["volume"]])
  assert_double(value[["volume_usd"]])
  assert_double(value[["volume_notional"]])
  assert_double(value[["price_change"]])
  assert_double(value[["estimated_delivery_price"]])
  assert_double(value[["mark_iv"]])
  assert_double(value[["underlying_price"]])
  assert_character(value[["underlying_index"]])
  assert_double(value[["interest_rate"]])
  assert_double(value[["current_funding"]])
  assert_double(value[["funding_8h"]])
  return(value)
}

assert_args_DeribitMarketData__get_book_summary_by_instrument <- function(instrument_name) {
  assert_scalar_character(instrument_name)
  return(invisible(NULL))
}

assert_return_DeribitMarketData__get_book_summary_by_instrument <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("instrument_name", "base_currency", "quote_currency", "datetime", "mid_price", "bid_price", "ask_price", "last", "mark_price", "high", "low", "open_interest", "volume", "volume_usd", "volume_notional", "price_change", "estimated_delivery_price", "mark_iv", "underlying_price", "underlying_index", "interest_rate", "current_funding", "funding_8h"))
  assert_character(value[["instrument_name"]])
  assert_no_missing_values(value[["instrument_name"]])
  assert_character(value[["base_currency"]])
  assert_no_missing_values(value[["base_currency"]])
  assert_character(value[["quote_currency"]])
  assert_no_missing_values(value[["quote_currency"]])
  assert_datetime(value[["datetime"]])
  assert_no_missing_values(value[["datetime"]])
  assert_double(value[["mid_price"]])
  assert_double(value[["bid_price"]])
  assert_double(value[["ask_price"]])
  assert_double(value[["last"]])
  assert_double(value[["mark_price"]])
  assert_double(value[["high"]])
  assert_double(value[["low"]])
  assert_double(value[["open_interest"]])
  assert_double(value[["volume"]])
  assert_double(value[["volume_usd"]])
  assert_double(value[["volume_notional"]])
  assert_double(value[["price_change"]])
  assert_double(value[["estimated_delivery_price"]])
  assert_double(value[["mark_iv"]])
  assert_double(value[["underlying_price"]])
  assert_character(value[["underlying_index"]])
  assert_double(value[["interest_rate"]])
  assert_double(value[["current_funding"]])
  assert_double(value[["funding_8h"]])
  return(value)
}

assert_args_deribit_base_url <- function(url) {
  assert_scalar_character(url)
  return(invisible(NULL))
}

assert_return_deribit_base_url <- function(value) {
  assert_scalar_character(value)
  return(value)
}

assert_return_empty_dt_instruments <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("instrument_name", "instrument_id", "kind", "instrument_type", "base_currency", "quote_currency", "counter_currency", "settlement_currency", "settlement_period", "price_index", "is_active", "state", "expiration_datetime", "creation_datetime", "contract_size", "tick_size", "min_trade_amount", "maker_commission", "taker_commission", "strike", "option_type", "max_leverage"))
  assert_character(value[["instrument_name"]])
  assert_no_missing_values(value[["instrument_name"]])
  assert_integer(value[["instrument_id"]])
  assert_no_missing_values(value[["instrument_id"]])
  assert_character(value[["kind"]])
  assert_no_missing_values(value[["kind"]])
  assert_character(value[["instrument_type"]])
  assert_no_missing_values(value[["instrument_type"]])
  assert_character(value[["base_currency"]])
  assert_no_missing_values(value[["base_currency"]])
  assert_character(value[["quote_currency"]])
  assert_no_missing_values(value[["quote_currency"]])
  assert_character(value[["counter_currency"]])
  assert_no_missing_values(value[["counter_currency"]])
  assert_character(value[["settlement_currency"]])
  assert_character(value[["settlement_period"]])
  assert_no_missing_values(value[["settlement_period"]])
  assert_character(value[["price_index"]])
  assert_no_missing_values(value[["price_index"]])
  assert_logical(value[["is_active"]])
  assert_no_missing_values(value[["is_active"]])
  assert_character(value[["state"]])
  assert_no_missing_values(value[["state"]])
  assert_datetime(value[["expiration_datetime"]])
  assert_no_missing_values(value[["expiration_datetime"]])
  assert_datetime(value[["creation_datetime"]])
  assert_no_missing_values(value[["creation_datetime"]])
  assert_double(value[["contract_size"]])
  assert_no_missing_values(value[["contract_size"]])
  assert_double(value[["tick_size"]])
  assert_no_missing_values(value[["tick_size"]])
  assert_double(value[["min_trade_amount"]])
  assert_no_missing_values(value[["min_trade_amount"]])
  assert_double(value[["maker_commission"]])
  assert_no_missing_values(value[["maker_commission"]])
  assert_double(value[["taker_commission"]])
  assert_no_missing_values(value[["taker_commission"]])
  assert_double(value[["strike"]])
  assert_character(value[["option_type"]])
  assert_double(value[["max_leverage"]])
  return(value)
}

assert_return_empty_dt_currencies <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("currency", "currency_long", "coin_type", "decimals", "min_confirmations", "min_withdrawal_fee", "withdrawal_fee", "network_fee", "in_cross_collateral_pool"))
  assert_character(value[["currency"]])
  assert_no_missing_values(value[["currency"]])
  assert_character(value[["currency_long"]])
  assert_no_missing_values(value[["currency_long"]])
  assert_character(value[["coin_type"]])
  assert_no_missing_values(value[["coin_type"]])
  assert_integer(value[["decimals"]])
  assert_integer(value[["min_confirmations"]])
  assert_double(value[["min_withdrawal_fee"]])
  assert_double(value[["withdrawal_fee"]])
  assert_double(value[["network_fee"]])
  assert_logical(value[["in_cross_collateral_pool"]])
  return(value)
}

assert_return_empty_dt_ticker <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("instrument_name", "datetime", "state", "last_price", "mark_price", "index_price", "best_bid_price", "best_bid_amount", "best_ask_price", "best_ask_amount", "settlement_price", "min_price", "max_price", "open_interest", "mark_iv", "underlying_price", "interest_rate", "interest_value", "current_funding", "funding_8h", "estimated_delivery_price", "stats_high", "stats_low", "stats_price_change", "stats_volume", "stats_volume_usd", "stats_volume_notional", "greeks_delta", "greeks_gamma", "greeks_vega", "greeks_theta", "greeks_rho"))
  assert_character(value[["instrument_name"]])
  assert_no_missing_values(value[["instrument_name"]])
  assert_datetime(value[["datetime"]])
  assert_no_missing_values(value[["datetime"]])
  assert_character(value[["state"]])
  assert_no_missing_values(value[["state"]])
  assert_double(value[["last_price"]])
  assert_double(value[["mark_price"]])
  assert_double(value[["index_price"]])
  assert_double(value[["best_bid_price"]])
  assert_double(value[["best_bid_amount"]])
  assert_double(value[["best_ask_price"]])
  assert_double(value[["best_ask_amount"]])
  assert_double(value[["settlement_price"]])
  assert_double(value[["min_price"]])
  assert_double(value[["max_price"]])
  assert_double(value[["open_interest"]])
  assert_double(value[["mark_iv"]])
  assert_double(value[["underlying_price"]])
  assert_double(value[["interest_rate"]])
  assert_double(value[["interest_value"]])
  assert_double(value[["current_funding"]])
  assert_double(value[["funding_8h"]])
  assert_double(value[["estimated_delivery_price"]])
  assert_double(value[["stats_high"]])
  assert_double(value[["stats_low"]])
  assert_double(value[["stats_price_change"]])
  assert_double(value[["stats_volume"]])
  assert_double(value[["stats_volume_usd"]])
  assert_double(value[["stats_volume_notional"]])
  assert_double(value[["greeks_delta"]])
  assert_double(value[["greeks_gamma"]])
  assert_double(value[["greeks_vega"]])
  assert_double(value[["greeks_theta"]])
  assert_double(value[["greeks_rho"]])
  return(value)
}

assert_return_empty_dt_order_book <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("instrument_name", "datetime", "side", "level", "price", "amount"))
  assert_character(value[["instrument_name"]])
  assert_no_missing_values(value[["instrument_name"]])
  assert_datetime(value[["datetime"]])
  assert_no_missing_values(value[["datetime"]])
  assert_character(value[["side"]])
  assert_no_missing_values(value[["side"]])
  assert_integer(value[["level"]])
  assert_no_missing_values(value[["level"]])
  assert_double(value[["price"]])
  assert_no_missing_values(value[["price"]])
  assert_double(value[["amount"]])
  assert_no_missing_values(value[["amount"]])
  return(value)
}

assert_return_empty_dt_index_price <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("index_name", "index_price", "estimated_delivery_price"))
  assert_character(value[["index_name"]])
  assert_no_missing_values(value[["index_name"]])
  assert_double(value[["index_price"]])
  assert_double(value[["estimated_delivery_price"]])
  return(value)
}

assert_return_empty_dt_dvol_candles <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("currency", "datetime", "resolution", "open", "high", "low", "close"))
  assert_character(value[["currency"]])
  assert_no_missing_values(value[["currency"]])
  assert_datetime(value[["datetime"]])
  assert_no_missing_values(value[["datetime"]])
  assert_character(value[["resolution"]])
  assert_no_missing_values(value[["resolution"]])
  assert_double(value[["open"]])
  assert_no_missing_values(value[["open"]])
  assert_double(value[["high"]])
  assert_no_missing_values(value[["high"]])
  assert_double(value[["low"]])
  assert_no_missing_values(value[["low"]])
  assert_double(value[["close"]])
  assert_no_missing_values(value[["close"]])
  return(value)
}

assert_return_empty_dt_funding_rate_history <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("instrument_name", "datetime", "index_price", "prev_index_price", "interest_8h", "interest_1h"))
  assert_character(value[["instrument_name"]])
  assert_no_missing_values(value[["instrument_name"]])
  assert_datetime(value[["datetime"]])
  assert_no_missing_values(value[["datetime"]])
  assert_double(value[["index_price"]])
  assert_double(value[["prev_index_price"]])
  assert_double(value[["interest_8h"]])
  assert_double(value[["interest_1h"]])
  return(value)
}

assert_return_empty_dt_funding_rate_value <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("instrument_name", "start_datetime", "end_datetime", "funding_rate_value"))
  assert_character(value[["instrument_name"]])
  assert_no_missing_values(value[["instrument_name"]])
  assert_datetime(value[["start_datetime"]])
  assert_no_missing_values(value[["start_datetime"]])
  assert_datetime(value[["end_datetime"]])
  assert_no_missing_values(value[["end_datetime"]])
  assert_double(value[["funding_rate_value"]])
  return(value)
}

assert_return_empty_dt_trade <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("trade_id", "instrument_name", "datetime", "trade_seq", "direction", "price", "amount", "index_price", "mark_price", "iv", "tick_direction", "contracts", "liquidation"))
  assert_character(value[["trade_id"]])
  assert_no_missing_values(value[["trade_id"]])
  assert_character(value[["instrument_name"]])
  assert_no_missing_values(value[["instrument_name"]])
  assert_datetime(value[["datetime"]])
  assert_no_missing_values(value[["datetime"]])
  assert_integer(value[["trade_seq"]])
  assert_character(value[["direction"]])
  assert_no_missing_values(value[["direction"]])
  assert_double(value[["price"]])
  assert_no_missing_values(value[["price"]])
  assert_double(value[["amount"]])
  assert_no_missing_values(value[["amount"]])
  assert_double(value[["index_price"]])
  assert_double(value[["mark_price"]])
  assert_double(value[["iv"]])
  assert_integer(value[["tick_direction"]])
  assert_double(value[["contracts"]])
  assert_character(value[["liquidation"]])
  return(value)
}

assert_return_empty_dt_book_summary <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("instrument_name", "base_currency", "quote_currency", "datetime", "mid_price", "bid_price", "ask_price", "last", "mark_price", "high", "low", "open_interest", "volume", "volume_usd", "volume_notional", "price_change", "estimated_delivery_price", "mark_iv", "underlying_price", "underlying_index", "interest_rate", "current_funding", "funding_8h"))
  assert_character(value[["instrument_name"]])
  assert_no_missing_values(value[["instrument_name"]])
  assert_character(value[["base_currency"]])
  assert_no_missing_values(value[["base_currency"]])
  assert_character(value[["quote_currency"]])
  assert_no_missing_values(value[["quote_currency"]])
  assert_datetime(value[["datetime"]])
  assert_no_missing_values(value[["datetime"]])
  assert_double(value[["mid_price"]])
  assert_double(value[["bid_price"]])
  assert_double(value[["ask_price"]])
  assert_double(value[["last"]])
  assert_double(value[["mark_price"]])
  assert_double(value[["high"]])
  assert_double(value[["low"]])
  assert_double(value[["open_interest"]])
  assert_double(value[["volume"]])
  assert_double(value[["volume_usd"]])
  assert_double(value[["volume_notional"]])
  assert_double(value[["price_change"]])
  assert_double(value[["estimated_delivery_price"]])
  assert_double(value[["mark_iv"]])
  assert_double(value[["underlying_price"]])
  assert_character(value[["underlying_index"]])
  assert_double(value[["interest_rate"]])
  assert_double(value[["current_funding"]])
  assert_double(value[["funding_8h"]])
  return(value)
}

